# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsGridProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  inhibit_all_warnings!
  use_frameworks!

  pod 'MJRefresh', '~> 3.4.3'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYModel', '~> 1.0.4'
end
